/*
DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  phone VARCHAR(250) DEFAULT NULL
);
*/